/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/rat/db/set DETECTOR experiment "darkbox"
/rat/db/set DETECTOR geo_file "darkbox/darkbox.geo"

/run/initialize

# BEGIN EVENT LOOP
/rat/proc simpledaq
/rat/proc count
/rat/procset update 10

/rat/proclast outroot
/rat/procset file "scattering_green.root"
#END EVENT LOOP

/generator/add combo pbomb:point:uniform
/generator/vtx/set 1000 500
/generator/pos/set 321 0 0

/run/beamOn 1000

